export const NavItems = [
    { name: "Slider", 
    links: [
        {title: 'Add Slider', to: '/addslider'},
        {title: 'Slider Detail', to: '/sliderdetail'},
],
    open: false,
},
{ name: "Photos", 
    links: [
        {title: 'Add photo', to: '/addphotos'},
        {title: 'Photo Detail', to: '/photodetail'},
],
    open: false,
},
{ name: "Products", 
    links: [
        {title: 'Add Products', to: '/addproducts'},
        {title: 'Products Detail', to: '/productdetail'},
],
    open: false,
},
{ name: "Instagram", 
    links: [
        {title: 'Add Instagram', to: '/addinstagram'},
        {title: 'Isntagram Detail', to: '/instagramdetail'},
],
    open: false,
},
{ name: "Logo", 
    links: [
        {title: 'Logo Detail', to: '/logodetail'},
],
    open: false,
},
{ name: "Settings", 
    links: [
        {title: 'Settings Detail', to: '/settingdetail'},
],
    open: false,
},
{ name: "Contact", 
    links: [
        {title: 'Contact Detail', to: '/contactdetail'},
],
    open: false,
},
{ name: "Message", 
    links: [
        {title: 'Message Detail', to: '/messagedetail'},
],
    open: false,
},
{ name: "FAQs", 
    links: [
        {title: 'Add FAQs', to: '/addfaq'},
        {title: 'FAQs Detail', to: '/faqdetail'},
        {title: 'Update FAQs', to: '/updatefaq/:id'},
],
    open: false,
},
]